### ISSUE TITLE
Parties with 0 mandates should appear last

### ISSUE THREAD

**Issue by uriklar** [V2015/election-polls-frontend#5]

**Comment by yuvii** [comment]
@uriklar 
This happens because some of the data returns `null` instead of `0`. We can solve this on the directive level (just collect the data and resort it ourselves), but I think the cleaner solution is to fix it on the data-level. Can you tell me where the app gets the information from? Can we control that information?

**Comment by uriklar** [comment]
I see. The data comes from a Rails backend I set up. I'll take care of it. Thanks

**Comment by yuvii** [comment]
:+1:
